export const images={
    logo: require("../assets/Logo/Logo/Logo.png"),
    bubbles: require("../assets/images/Group-1153/Group-1153.png"),
    checkMark: require("../assets/myIcon/myIcon.png"),
    pinLocation: require("../assets/pin/pin.png"),
    home1: require("../assets/images/home1/home1.png"),
    home2: require("../assets/images/home2/home2.png"),
    star: require("../assets/images/star/star.png"),
    pin: require("../assets/images/pin/pin.png"),
    clock: require("../assets/images/clock/clock.png"),
    Share: require("../assets/images/Share/Share.png"),
    Back: require("../assets/images/Back/Back.png"),
    direction: require("../assets/images/direction/direction.png"),
    badge: require("../assets/images/badge/badge.png"),
    after: require("../assets/images/after/after.png"),
    map: require("../assets/images/map/map.png"),
    plus: require("../assets/images/plus/plus.png"),
    pencil: require("../assets/images/pencil/pencil.png"),
    shop: require("../assets/images/shop/shop.png"),
    humantwo: require("../assets/images/humantwo/humantwo.png"),
    humanone: require("../assets/images/humanone/humanone.png"),
    Close: require("../assets/images/Close/Close.png")
};