export const routes={
LOGIN:'Login',
REGISTER:'Register',
ABOUT:'About',
SECCURE_ACCOUNT:'Secure Account',
PREFERENCES:'Preferences',
FORGOT_PASSWORD:'Forgot Password',
NEAR_ME:'Near Me',
WELCOME: 'Welcome',
Venue_Profile: "Venue Profile",
REVIEW: "Review",
PLAN_TRIP: 'Plan Trip',
CUSTOM_TRIP: "Custom Trip",
TRIP_LOCATION: 'TripLocation',
PLANNED_DATES: "Planned",
BLOG: "Blog",
MORE: 'More', 
NOTIFICATION: 'Notification',
ACCOUNT_SETTINGS: 'Account Settings',
};